const container = document.querySelector('#container')

  const col1 = document.createElement('div')

    const box1 = document.createElement('div')
    col1.appendChild(box1)
    const box2 = document.createElement('div')
    col1.appendChild(box2)
    const box3 = document.createElement('div')
    col1.appendChild(box3)
    const box4 = document.createElement('div')
    col1.appendChild(box4)
    const box5 = document.createElement('div')
    col1.appendChild(box5)
    const box6 = document.createElement('div')
    col1.appendChild(box6)
    const box7 = document.createElement('div')
    col1.appendChild(box7)
    const box8 = document.createElement('div')
    col1.appendChild(box8)
    const box9 = document.createElement('div')
    col1.appendChild(box9)
    const box10 = document.createElement('div')
    col1.appendChild(box10)
    const box11 = document.createElement('div')
    col1.appendChild(box11)
    const box12 = document.createElement('div')
    col1.appendChild(box12)
    const box13 = document.createElement('div')
    col1.appendChild(box13)
    const box14 = document.createElement('div')
    col1.appendChild(box14)
    const box15 = document.createElement('div')
    col1.appendChild(box15)
    const box16 = document.createElement('div')
    col1.appendChild(box16)

  container.appendChild(col1)

  const col2 = document.createElement('div')

  const b1 = document.createElement('div')
  col2.appendChild(b1)
  const b2 = document.createElement('div')
  col2.appendChild(b2)
  const b3 = document.createElement('div')
  col2.appendChild(b3)
  const b4 = document.createElement('div')
  col2.appendChild(b4)
  const b5 = document.createElement('div')
  col2.appendChild(b5)
  const b6 = document.createElement('div')
  col2.appendChild(b6)
  const b7 = document.createElement('div')
  col2.appendChild(b7)
  const b8 = document.createElement('div')
  col2.appendChild(b8)
  const b9 = document.createElement('div')
  col2.appendChild(b9)
  const b10 = document.createElement('div')
  col2.appendChild(b10)
  const b11 = document.createElement('div')
  col2.appendChild(b11)
  const b12 = document.createElement('div')
  col2.appendChild(b12)
  const b13 = document.createElement('div')
  col2.appendChild(b13)
  const b14 = document.createElement('div')
  col2.appendChild(b14)
  const b15 = document.createElement('div')
  col2.appendChild(b15)
  const b16 = document.createElement('div')
  col2.appendChild(b16)

container.appendChild(col2)